### ISSUE TITLE
Seems another systemd service needs the fix mentioned in #5

### ISSUE THREAD

**Issue by sjorge** [joyent/centos-lx-brand-image-builder#7]
systemd-localed.service

**Comment by chorrell** [comment]
Ah, right, which is needed for `localectl`

**Comment by sjorge** [comment]
Bingo! Finally got around to reprovisioning some zones. I had removed the override stuff from my user-script and stuff broke (salt setting the locales)

**Comment by chorrell** [comment]
OK, the fix is in, will be part of the next image release.

**Comment by sjorge** [comment]
Great :) I assume also for the other systemd images (debian, ubuntu,...)?

**Comment by chorrell** [comment]
Just CentOS for now, will be adding the others later.
