### ISSUE TITLE
Provision image fail  for  centos7.2  and 7.1 lx brand zone

### ISSUE THREAD

**Issue by webloginwu** [joyent/centos-lx-brand-image-builder#8]
install log on kvm:
       ./install -d /data/chroot -m http://vault.centos.org/centos/7.1.1503/os/x86_64/Packages/  -r centos-release-7-1.1503.el7.centos.2.8.x86_64.rpm  -i test-lx-centos-7.2 -p "CentOS 7.2 LX Brand" -D "CentOS 7.2 64-bit lx-brand image." -u https://docs.joyent.com/images/container-native-linux

[dataset_install_2016-10-22-19_50.txt](https://github.com/joyent/centos-lx-brand-image-builder/files/545797/dataset_install_2016-10-22-19_50.txt)

---

install log in global zone
        /opt/centos-lx-brand-image-builder/create-lx-image -t  `ls /opt/centos-lx-brand-image-builder/*.gz`  -k 3.13.0 -m 20160117T201601Z -i test-lx-centos-7.2 -d "CentOS 7.2 64-bit lx-brand image." -u https://docs.joyent.com/images/container-native-linux

```
                           ==> Creating dataset for image creation...
                            ==> The dataset is zones/test-lx-centos-7.2-20161022
                            ==>
                            ==> Installing the tar archive, this will take a few minutes...
                            ==> Modifying the image to work in a zone...
                            ====> Creating /native directories...
                            ====> done.
                            ====> Creating the /var/ld/ld.config file...
                            ====> Created "/zones/test-lx-centos-7.2-20161022/root/var/ld/ld.config"
                            ====> Created "/zones/test-lx-centos-7.2-20161022/root/var/ld/64/ld.config"
                            ====> Setting up fstab...
                            ==> Image modification complete.
                            ==> Creating image file:
                            ====> Creating snapshot...
                            ====> Doing a zfs send. This may take a few minutes...
                            ====> Done.
                            ====> Cleaning up...
                            ==> Image File created!
                            ==>
                            ==> Creating manifest file...
                            ==> done!
                            ==>
                            *** Image creation complete ***
                            ==> Image files:
                            test-lx-centos-7.2-20161022.json
                            test-lx-centos-7.2-20161022.tar.gz
                            test-lx-centos-7.2-20161022.zfs.gz
```

---
## smartos gloable zone: SmartOS (build: 20160906T181054Z)

kvm version on smartos: 

cat /etc/redhat-release 
## CentOS Linux release 7.2.1511 (Core) 

json file:
{
  "alias": "dataset_test_lx",
  "brand": "lx",
  "hostname": "dataset_test_lx",
  "kernel_version": "3.13.0",
  "max_physical_memory": 2048,
  "quota": 50,
  "image_uuid": "4617aad2-984f-11e6-84ac-67dd688621dd",
  "resolvers": ["172.17.1.10","114.114.114.114"],
  "nics": [
    {
                     "nic_tag": "admin",
                     "ips": ["dhcp"]
    }
  ]
}

---

imgadm install -m  test-lx-centos-7.2-20161022.json  -f test-lx-centos-7.2-20161022.zfs.gz
I use vmadm to creart lx zone ,get the result:
timed out waiting for /var/svc/provisioning to move for 9135d416-7a32-699a-f333-ab600d41d99f

**Comment by chorrell** [comment]
It looks like the image you created is ok. The "timed out waiting for /var/svc/provisioning to move" error usually means something is causing the provision to fail in some way. One possible cause could be a failure when setting up the network for the instance. Also, in the failed instance there should be a log called `/var/log/triton.log`. This is where the guest tools log their output and the guest tools are responsible for changing `/var/svc/provisioning` to /var/svc/provision_success`. The log might indicate where things are failing.

**Comment by webloginwu** [comment]
it's file permission problem,
when i use salt to copy /opt/centos-lx-brand-image-builder/ directory ,all file permission is 644.
thank you for your help!!
 close #8

**Comment by webloginwu** [comment]
close #8
